project_id = "yfhdzkjuhxsbxklfgdut"

[functions.n8n-error-webhook]
verify_jwt = false

[functions.notifications-api]
verify_jwt = false

[functions.sheets-proxy]
verify_jwt = false

[functions.leads-webhook]
verify_jwt = false

[functions.conversation-memory]
verify_jwt = false
