project_id = "yfhdzkjuhxsbxklfgdut"

[functions.conversation-memory]
verify_jwt = false

[functions.conversation-memory-latest]
verify_jwt = false

[functions.lead-webhook]
verify_jwt = false

[functions.n8n-error-webhook]
verify_jwt = false

[functions.notifications-api]
verify_jwt = false
