// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfhdzkjuhxsbxklfgdut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmaGR6a2p1aHhzYnhrbGZnZHV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2MzM1NzcsImV4cCI6MjA4NzIwOTU3N30.8djIuFSOgDLHik_vPoYBATHu4uckf_lsNTCWUHd85mM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});